### ISSUE TITLE
Tweets are getting hidden in the main thread

### ISSUE THREAD

**Issue by fernandoabolafio** [tiagoalvesdulce/dcrtimestamptweet#5]
The bot tweets are getting hidden in the thread where it is invoked. It is unclear what is the main cause of it, but it is definitely being marked as spam. 
If you look at this twitter tos: https://help.twitter.com/en/rules-and-policies/twitter-automation, you can see that we may fit in the category of spam by twiting almost the same content every time. 
This article also explains what maybe is happening: https://www.wired.com/story/twitter-will-begin-hiding-all-tweets-from-suspect-accounts/.
> Those whose tweets are deemed to be "disruptive," but that don't violate Twitter's policies outright, will be secluded at the bottom of a conversation thread or search result, to make room for more productive and respectful conversations. Some of the new signals Twitter will consider include whether you've confirmed your email address, whether you've created multiple accounts from the same IP address, and whether you're frequently blocked by accounts you interact with. Tweets that get filtered this way—as long as they don't violate Twitter's policies—won't be removed, but you will have to click "Show more replies," or elect to "show everything" in your search settings in order to view them.

It's important to notice that the tweets are not being deleted. If you go to the bot Tweet & Replies section you can see all the replies made by the bot in there:
https://twitter.com/dcrtimestampbot/with_replies.

Some actions we can take:
 - Create a set of different greetings to be sent at the beginning of the message.
 - Direct message the user who have invoked the bot with the results, so even if the tweet gets hidden, the user will know that worked.
- Add ipfs and dcrtime hashes in the body of the message so the text content will be different every time. 
- [Complex one] Create a minimum delay between replies in the same thread.

**Comment by vctt94** [comment]
I think `Direct message the user who have invoked the bot with the results, so even if the tweet gets hidden, the user will know that worked.` would be not to complicated to achieve and would solve the problem for now. 

Not sure if creating a set of different greetings would solve the problem as they will still repeat between the set. 
Also not much a fan of adding the hash in the body message, as it would occupy almost all the tweet and would not add much information for the user.

I think we can also try pasting part of the text being anchored, like 140 characters, this way the tweet would be different most of the time.

**Comment by fernandoabolafio** [comment]
Yes, that's a good start.
> I think Direct message the user who have invoked the bot with the results, so even if the tweet gets hidden, the user will know that worked. would be not too complicated to achieve and would solve the problem for now.

Maybe it won't solve the problem, but since we don't clearly know what twitter is using to flag the tweets as spam, as more things we can address, the better are the odds at our side. Also switching between a set of 8/9 spams is easy to implement and can make the bot a bit more "fun".
> Not sure if creating a set of different greetings would solve the problem as they will still repeat between the set.

Yeah, we can leave that for now.
> Also not much a fan of adding the hash in the body message, as it would occupy almost all the tweet and would not add much information for the user.

Don't think this is a good idea. We are timestamping the entire thread, so there is not really a point of pasting just part of the last tweet
> I think we can also try pasting part of the text being anchored, like 140 characters, this way the tweet would be different most of the time.

**Comment by fernandoabolafio** [comment]
PR #6 actually did the job.
